
keyboard.bindings = [
{ key = ",", mods = "Control", mode = "~Search", action = "ToggleViMode" }]

[window]
dynamic_padding = true
padding = { x = 10, y = 10 }
decorations = "None"
startup_mode = "Maximized"

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
size = 12.0

[cursor]
style = "Beam"
unfocused_hollow = true

[scrolling]
history = 10000
multiplier = 3

[bell]
animation = "EaseOutExpo"
duration = 125
color = "0xff5555"

# colors (miasma) https://github.com/xero/miasma.nvim
[colors]
indexed_colors = [{ index = 16, color = "0x222222"}]

# Primary colors
[colors.primary]
background = "#222222"
foreground = "#c2c2b0"

# Normal colors
[colors.normal]
black = "#222222"
red = "#685742"
green = "#5f875f"
yellow = "#b36d43"
blue = "#78824b"
magenta = "#bb7744"
cyan = "#c9a554"
white = "#d7c483"

# Bright colors
[colors.bright]
black = "#666666"
red = "#685742"
green = "#5f875f"
yellow = "#b36d43"
blue = "#78824b"
magenta = "#bb7744"
cyan = "#c9a554"
white = "#d7c483"

[general]
working_directory = "c:\\users\\ohw"

[terminal]
shell = "pwsh"
